### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by chairmanview** [muarine/component#1]
java.net.ConnectException: Connection refused: no further information
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:677)
    at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:436)
    at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1446)

**Comment by muarine** [comment]
clone后component-web下的system.properties需要自行配置memcache连接地址和第三方平台的账户信息，具体可看配置文件的注释。
